import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './app/App';
import { BootErrorBoundary } from './app/BootErrorBoundary';
import './styles/tokens.css';
import './styles/global.css';

const rootEl = document.getElementById('root');
if (!rootEl) {
  throw new Error('Root element #root not found in index.html');
}

// Register the PWA service worker (auto-generated by vite-plugin-pwa).
// registerSW.js is emitted to /dist/ at build time; safe to import
// unconditionally because vite-plugin-pwa handles the noop in dev.
import('virtual:pwa-register')
  .then(({ registerSW }) => {
    registerSW({ immediate: true });
  })
  .catch(() => {
    // virtual module not present (e.g. dev mode with devOptions.enabled=false).
    // Silent — the app still works as a regular web app.
  });

createRoot(rootEl).render(
  <React.StrictMode>
    <BootErrorBoundary>
      <App />
    </BootErrorBoundary>
  </React.StrictMode>,
);
